[package]
name = "docbunker-renderer-api-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
docbunker-renderer-api = { path = "../.." }

[workspace]

[[bin]]
name = "format_detect"
path = "fuzz_targets/format_detect.rs"
test = false
doc = false
bench = false
