//! Session and document identity types.

/// Backend kind, for logging and diagnostics only.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SandboxKind {
    /// In-process mock (development/tests only, no isolation).
    Mock,
    /// Bare worker subprocess (development only, no isolation; Phase 2).
    Subprocess,
    /// Linux `runsc`/gVisor sandbox (Phase 4).
    Runsc,
    /// Linux VM sandbox under QEMU with a native host accelerator.
    QemuVm,
}

/// Opaque sandbox session handle. Ids are generated by the backend, never
/// derived from user input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SandboxSession {
    pub id: u64,
    pub kind: SandboxKind,
}

/// Opaque document id assigned by the backend.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct DocumentId(pub u64);

/// A document entering the sandbox. Bytes only — never paths.
#[derive(Debug)]
pub struct DocumentInput {
    pub data: Vec<u8>,
}

impl DocumentInput {
    pub fn new(data: Vec<u8>) -> Self {
        Self { data }
    }
}
